### ISSUE TITLE
Add craft for creating a command/console

### ISSUE THREAD

**Issue by abishekrsrikaanth** [mikeerickson/laravel-craftsman#11]
Can you add the feature to craft a laravel command. I use this pretty much every day in my projects, but when I use it on a lumen project I have to create laravel commands from scratch. If you could add a craft to simply this, it would be great.

```
laravel-craftsman craft:command name --options=foo,bar --arguments=foofoo,barbar
```

**Comment by mikeerickson** [comment]
Hello 

Yes, I can add this command, seems like a worthy addition. I will put it on the short list and try to get it completed over the weekend.

**Comment by abishekrsrikaanth** [comment]
Any update on this?

**Comment by mikeerickson** [comment]
It was posted on Sunday, it is in the 1.8 version, the repo readme has details
