### ISSUE TITLE
Feature Request: Allow craft:class to use a template and define path to save the class

### ISSUE THREAD

**Issue by abishekrsrikaanth** [mikeerickson/laravel-craftsman#2]
Can you add an enhancement to define a template using a path and also define a path to save the class?

**Comment by mikeerickson** [comment]
I am not sure what you mean? 

If you execute 

```
laravel-craftsman craft:class App/Services/Contacts/MyClass ...
```

The class will be created in

```
App
—Services
    —Contacts
         — MyClass
```

**Comment by mikeerickson** [comment]
I will update documentation to clarify this 

If you are thinking of something else, please let me know

**Comment by mikeerickson** [comment]
@abishekrsrikaanth With regards to defining the path to the template, you can use the `config.php` path in the installed path of the laravel-craftsman app.  Here you can customize the path to each of the various templates.

```
~/.composer/vendor/<username>/laravel-craftsman/builds/config.php
```

```
return [
    "templates" => [

        'class' => 'templates/class.user.mustache',

    ],
];
```

**Comment by abishekrsrikaanth** [comment]
Thanks for clarifying the save path. That definitely helps. But my question about using a template was about setting the template using an argument instead of the config file. There are a variety of classes that one requires to create in addition to views, models, controllers, etc. Let's say for example `FormRequests`, `Jobs`, `ApiResources` that may use a custom traits or interfaces or extends abstract classes. If I create a few mustache templates within my project directory, it would be easier to do 

```
> laravel-craftsman 
          craft:class App\Domains\Account\Jobs\OnCreateUser 
          --template="templates/sync.job.mustache"
```
This way we could have project specific templates instead of using the global templates.
I hope that makes sense.

**Comment by mikeerickson** [comment]
I understand what you are asking and will add this as a request.  I can see how this would be beneficial 🤓

**Comment by abishekrsrikaanth** [comment]
Sound good. Look forward to this.

**Comment by mikeerickson** [comment]
@abishekrsrikaanth while considering this feature, you have defined 👎 

```
  ...
  --template="templates/sync.job.mustache"
  ...
```

Are you thinkinig of project specific templates, or global templates (those available in all projects)

**Comment by mikeerickson** [comment]
@abishekrsrikaanth after thinking about this, I am going to implement using both, with default being the application templates directory.  In addition, you define `<project>` which will use the current project directory.

```
laravel-craftsman craft:class --template "templates/templates/sync.job.mustache"
laravel-craftsman craft:class --template "<project>/templates/templates/sync.job.mustache"
```

**Comment by mikeerickson** [comment]
@abishekrsrikaanth This has been added in the latest release (version 1.1)

https://github.com/mikeerickson/laravel-craftsman/releases/tag/1.1.1
