### ISSUE TITLE
Error on craft:migration

### ISSUE THREAD

**Issue by abishekrsrikaanth** [mikeerickson/laravel-craftsman#3]
When I run 

```
laravel-craftsman craft:migration create_products_nutritional_facts_table 
          --tablename products_nutritional_facts 
          --fields product_id:integer, serving_size:integer
          --model ProductsNutrionalFact
```

I get the following error.

```
 Too many arguments, expected arguments "command" "name".
```
Am i missing something? Also, can the `--model` argument be made optional?

**Comment by mikeerickson** [comment]
@abishekrsrikaanth I will debug this further, but in the meantime, if you surround the `--fields` value with quotes, all should work as expected.

With regards to request for making `--models` property optional, i have created a separate issue for this 

Allow migration modeil optional -- https://github.com/mikeerickson/laravel-craftsman/issues/4

**Comment by mikeerickson** [comment]
@abishekrsrikaanth OK, found the issue.  If you have spaces in the field list, you must surround the value in quotes

```bash
laravel-craftsman craft:migration test --fields "product_id:integer, serving_size:integer" ...
or
laravel-craftsman craft:migration test --fields "product_id:integer,serving_size:integer" ...
```

**Comment by mikeerickson** [comment]
@abishekrsrikaanth I have added the ability to generate migrations without require `--model` or `--tablename` options

https://github.com/mikeerickson/laravel-craftsman/releases/tag/1.1.2
