### ISSUE TITLE
don't install codedungeon/laravel-craftsman

### ISSUE THREAD

**Issue by DavidCao626** [mikeerickson/laravel-craftsman#7]
don't install codedungeon/laravel-craftsman:
> vagrant@homestead:~/Code/sfqnh-app$ composer global require codedungeon/laravel-craftsman
Changed current directory to /home/vagrant/.composer
Using version ^1.6 for codedungeon/laravel-craftsman
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: don't install codedungeon/laravel-craftsman 1.6.3
    - Conclusion: don't install codedungeon/laravel-craftsman 1.6.1
    - Conclusion: remove illuminate/contracts v5.6.23
    - Installation request for codedungeon/laravel-craftsman ^1.6 -> satisfiable by codedungeon/laravel-craftsman[1.6.0, 1.6.1, 1.6.3].
    - Conclusion: don't install illuminate/contracts v5.6.23
    - codedungeon/laravel-craftsman 1.6.0 requires laravel-zero/framework 5.8.* -> satisfiable by laravel-zero/framework[v5.8.0, v5.8.1, v5.8.2, v5.8.3, v5.8.4, v5.8.5].
    - laravel-zero/framework v5.8.0 requires illuminate/contracts 5.8.* -> satisfiable by illuminate/contracts[v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - laravel-zero/framework v5.8.1 requires illuminate/contracts 5.8.* -> satisfiable by illuminate/contracts[v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - laravel-zero/framework v5.8.2 requires illuminate/contracts 5.8.* -> satisfiable by illuminate/contracts[v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - laravel-zero/framework v5.8.3 requires illuminate/contracts 5.8.* -> satisfiable by illuminate/contracts[v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - laravel-zero/framework v5.8.4 requires illuminate/contracts 5.8.* -> satisfiable by illuminate/contracts[v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - laravel-zero/framework v5.8.5 requires illuminate/contracts 5.8.* -> satisfiable by illuminate/contracts[v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - Can only install one of: illuminate/contracts[v5.8.0, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.11, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.12, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.14, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.15, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.17, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.18, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.19, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.2, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.20, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.22, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.24, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.27, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.28, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.29, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.3, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.30, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.31, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.32, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.33, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.34, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.35, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.4, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.8, v5.6.23].
    - Can only install one of: illuminate/contracts[v5.8.9, v5.6.23].
    - Installation request for illuminate/contracts (locked at v5.6.23) -> satisfiable by illuminate/contracts[v5.6.23].
	Installation failed, reverting ./composer.json to its original content.

 php version：
> vagrant@homestead:~/Code/sfqnh-app$ php -v
PHP 7.2.5-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May  5 2018 05:00:15) ( NTS )Copyright (c) 1997-2018 The PHP Group Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.2.5-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies with blackfire v1.20.0~linux-x64-non_zts72, https://blackfire.io, by Blackfire

compose versionr：
> vagrant@homestead:~/Code/sfqnh-app$ composer -V
Composer version 1.9.0 2019-08-02 20:55:32

laravel version:
>Laravel Framework 5.8.30

**Comment by pxgamer** [comment]
Do you have another Laravel-based application globally installed? 🤔

I also get this as I have the Laravel Installer, and Laravel Zero installer installed (which are both currently using v6.x of the Illuminate packages.

**Comment by mikeerickson** [comment]
I can try and reproduce this issue with a fresh user account.  What operating system and version are you using so I can test accurately

**Comment by pxgamer** [comment]
Tested with Windows 10 (with platform reqs disabled) and Ubuntu 19.04

**Comment by mikeerickson** [comment]
@pxgamer that will take some time as I only have access to windows via Parallels.

**Comment by pxgamer** [comment]
With a fresh user account, it works fine for me. 👍

I was just interested if @DavidCao626 has a package installed globally that requires `^5.6` of `illuminate/contracts`.
